### ISSUE TITLE
Lovelace Card Template

### ISSUE THREAD

**Issue by epajfl00** [Apoc182/local_daikin#11]
I'm just curious why there seems to be 2 card templates.

1. This the standard template you use;
![image](https://github.com/Apoc182/local_daikin/assets/86779948/3a209650-1acf-41cd-85d4-407d194a46c5)

2. If the the 3 dots is selected at the top right corner, then this template is seem.
![image](https://github.com/Apoc182/local_daikin/assets/86779948/26d3eeef-28ee-4da1-a4a0-e5c5347d2a94)

This a much better view of what is going on, and nicely set out, even humidity is show.
Can this be the main template that is used for lovelace, instead?
Except that the friendly name is not displayed here, for some reason.

**Comment by ajvandr** [comment]
I don't think this is within the control of this integration, but is set by the platform when device class is hvac.
This project is 'simply' polling the device for the data to populate the hvac model in HA.

**Comment by Apoc182** [comment]
Hi @epajfl00. I have the same setup. As @ajvandr suggests, this is the UI and I have no explicit control over the card.

**Comment by epajfl00** [comment]
Not sure if I understand which climate UI is standard, the one we normally see, or the one that comes up if the 3 dots is pressed, or both?
I remember that the original Daikin solution Climate UI did not have the 3 dots option.
