### ISSUE TITLE
Auto mode issues with changing temperature

### ISSUE THREAD

**Issue by Apoc182** [Apoc182/local_daikin#14]
Unsure what is going on here, but when in auto mode, the unit seems to jump back to its old temp most of the time. Would be good to get confirmation this is happening to others.

**Comment by ajvandr** [comment]
If I try to set Auto set temp below 18degC I get 

Failed to call service climate/set_temperature. An exception occured: {'responses': [{'rsc': 4000, 'fr': '/dsiot/edge/adr_0100.dgc_status'}]}

If I set above 24degC it reverts to 18, but only the first time - subsequent settings up to the max are successful.
(actually it isn't as clear or predictable as that unfortunately.  I'm sure there's a pattern there I just can't see it.)
