### ISSUE TITLE
Integration into pyDaikin

### ISSUE THREAD

**Issue by fredrike** [Apoc182/local_daikin#19]
Hi,

It would be great to include v2.8.0 support to the official HA Daikin integration. I think that an update to pydaikin would be enough to get it to work. PyDaikin is built to be modular so the extension should not have to be super big.

https://github.com/fredrike/pydaikin

**Comment by fredrike** [comment]
Why did you close this?

I can help you integrate into pydaikin (perhaps copilot can do this for us) and the benifit woult be great.

If I write the code with help from this repo would you like to review and test it?

**Comment by Apoc182** [comment]
Hi @fredrike . 

Honestly, I don't remember. Perhaps it might have been because this isn't really an issue with this repository, but more of a suggestion for pydaikin.

In any case, yes I am happy to review your changes from this repo to pydaikin :)
