### ISSUE TITLE
Possible to show compressor speed?

### ISSUE THREAD

**Issue by brianbienvenu** [Apoc182/local_daikin#20]
Thanks for providing this code, from another Daikin v2.8.0 survivor. I think I've gotten temp/humidity reporting working in Lovelace by manually adding some template sensors by JackScottAU's method: https://github.com/home-assistant/core/issues/99251#issuecomment-2164522727

In the past, I could also see the outdoor unit compressor frequency (in Hz), which was useful to confirm what it's actually doing. Is it possible to get that data from the new API structure? I see a single mention of "rotationSpeed" in "New.Daikin.API.Communication.Documentation.pdf", but can't find anything else.

**Comment by blackout182** [comment]
Hi @brianbienvenu 

I can't see that information in the mobile app so it's going to be pretty difficult to do if it's there. I need something to reference when trying to work out where it's stored.

I'll look into it when I get some time though.

**Comment by Apoc182** [comment]
Hi @brianbienvenu 

I can't see that information in the mobile app so it's going to be pretty difficult to do if it's there. I need something to reference when trying to work out where it's stored.

I'll look into it when I get some time though.
