### ISSUE TITLE
Daikin AC are not working after update to 2024.8.1

### ISSUE THREAD

**Issue by dkam** [Apoc182/local_daikin#21]
My two Daikin's have stopped working since updating to 2024.8.1 - same issue reported with the included Daikin integration: 

https://github.com/home-assistant/core/issues/123550

**Comment by Apoc182** [comment]
This is strange, I have this update and no issues on my end. Are you able to send through the log for this integration?

**Comment by ajvandr** [comment]
No issues with my 2 Alira X units - my BRP072 units all fell over with HA 2024.8.0 and are working now with 8.2.

If you have BRP069xxx units you aren't using this integration.

**Comment by dkam** [comment]
I’ve rolled back to 2024.8.0 and they’re working again. I can move forward again and get the logs if you like. 

The head unit is FTXM50WVMA, which is an Alira X.  UniFi reports the wifi module as:  “Daikin AC Controller BRP069B41” - is there another way to confirm the model of wifi controller?
