### ISSUE TITLE
Being able to use attributes as a statisic

### ISSUE THREAD

**Issue by joelskyle** [Apoc182/local_daikin#22]
It would be great if we could access the outside_temperature, current_temperature, current_humidity, runtime_today and energy_today attributes each as their own statistic so that they can be used for historical trending and other reporting graphs.

**Comment by AndyFlysJabs** [comment]
Most of these things are available as attributes of the added local daikin device. In my HA I have the following fragment added to configuration.yaml to expose some of these things as unique (template) sensors for use in Node red. While its perfectly possible inside node red to deal with these as attributes where they are, to me it made more sense where I was using to expose as unique template sensor.

template:
    - sensor:
    - name: Outside_Temp_east
        state: >
          {{ '%0.1f' | format(state_attr('climate.local_daikin','outside_temperature') | float) }}
        unit_of_measurement: '°C'
        device_class: Temperature 

that's an example of the outside temperature. You deal with the other things you asked about in the same way.

If you look up your entity(s) on the developer section under the states tab (type local_daikin into the filter entites next to the magnifying glass) and then look in the 3rd column under attributes you'll see what is exposed and teh values of these.

Andy
