### ISSUE TITLE
Useful Information

### ISSUE THREAD

**Issue by epajfl00** [Apoc182/local_daikin#8]
I came across a document in Japanese at this link. 
https://ydn.jp/archives/12367

I've google translated it, but lost some of the formatting, but I think you may find this very useful with the work you are doing to improve and add further functionality. 
[New Daikin Communication.txt](https://github.com/user-attachments/files/15747215/New.Daikin.Communication.txt)

I hope you can use.

BR
Joseph..................

**Comment by Apoc182** [comment]
Thanks for this, lots of useful information. Might add it to the wiki/docs

**Comment by epajfl00** [comment]
Hi,
    I had time to review this doc I sent you and found a lot of duplication's and the lack of formatting didn't help, so I've gone through it and formatted the contents and now it much more legible, Hope it help you and others further.
You can update the Wiki contents.
[New Daikin API Communication Documentation.pdf](https://github.com/user-attachments/files/15798607/New.Daikin.API.Communication.Documentation.pdf)
